### ISSUE TITLE
Formula Error in Jacobi Iteration

### ISSUE THREAD

**Issue by albaaj17** [rachelslaybaugh/NE155#22]
In the parenthesis for the Jacobi Iterative method, it should be A - D not D - A.

**Comment by rachelslaybaugh** [comment]
Actually, I'm pretty sure that what is there is correct. If you look here: https://en.wikipedia.org/wiki/Jacobi_method, R = A-D, but they use -R in the algorithm, which is D-A. What is in my notes works out to be the same as what they have. The same is written somewhat less clearly here: http://mathworld.wolfram.com/JacobiMethod.html (because they define -L and -U), and somewhat more clearly here: http://www.maa.org/press/periodicals/loci/joma/iterative-methods-for-solving-iaxi-ibi-jacobis-method

**Comment by rachelslaybaugh** [comment]
@albaaj17 : did this answer your question?

**Comment by albaaj17** [comment]
Yes! Thanks
